swagger: "2.0"
info:
  version: "0.0.1"
  title: <%= appName %>
# basePath prefixes all resource paths
basePath: /api/gdam
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /:
    get:
      responses:
        200:
          description: OK
